//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodSchedule()
        {
            this.Reserves = new HashSet<Reserve>();
        }
    
        public long Id { get; set; }
        public long FoodId { get; set; }
        public bool BreakFast { get; set; }
        public bool Lunch { get; set; }
        public bool Dinner { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public System.DateTime AvailableDate { get; set; }
        public int AvailableCount { get; set; }
    
        public virtual Food Food { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserve> Reserves { get; set; }
    }
}
