//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDetail
    {
        public long Id { get; set; }
        public byte LanguageId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long FoodId { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Language Language { get; set; }
    }
}
