//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve
    {
        public long Id { get; set; }
        public long FoodScheduleId { get; set; }
        public System.DateTime ReserveDate { get; set; }
        public int ReserveCount { get; set; }
        public bool BreakFast { get; set; }
        public bool Lunch { get; set; }
        public bool Dinner { get; set; }
        public bool IsSold { get; set; }
        public string Description { get; set; }
        public long ReserveUserId { get; set; }
    
        public virtual FoodSchedule FoodSchedule { get; set; }
        public virtual User User { get; set; }
    }
}
